from torch import device, cuda

FOV = 90
FOV_FOCUS_RELAXATION = 2

DEVICE = device('cuda:0' if cuda.is_available() else 'cpu')

BUFFER_DISTANCE = 0.000045 # Approximately 5 meters (in terms of latitude/longitude)

LR_MODEL_THRESHOLD = 0.7
MR_MODEL_THRESHOLD = 0.4
NUM_CLASSES_MR = 7
IOU_THRESHOLD = 0.3
IOU_THRESHOLD_REMOVAL = 0.3
LARGEST_DISTANCE_TO_CHASE = 100

MAXIMUM_WALK_STEPS = 2
MAXIMUM_WALK_DISTANCE_DELTA = 70 
MAXIMUM_TRUSTED_DISTANCE = 30
MACRO_PITCH_ADJUSTMENT = 0.5
LIKELIHOOD_RATIO = 2
MAXIMUM_TRUSTED_DISTANCE = 30

CLASSES_TO_CHASE = [-1,1,2,3,4,5,6]
INTERRUPTION_CONFIDENCE = 1

